name: Cesium for Unreal
on: [push]
jobs:
  Windows:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install extra dependencies
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=User'
      - name: Build cesium-native
        run: |
          mkdir extern/build
          cd extern/build
          cmake .. -A x64
          cmake --build . --config Release --target install -- /maxcpucount:8
